defaults: &defaults
  working_directory: ~/app
  docker:
    - image: nikengp/node6:v0.1
tag_filter: &tag_filter
  tags:
    only: /.v*/
  branches:
    ignore: /.*/
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: test
      #     command: /build-scripts/lib-run-tests.sh
      # - run:
      #     name: build report
      #     command: /build-scripts/generate-test-report.sh
      #     when: always
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_artifacts:
      #     path: test-results
      #     prefix: test-results
      # - store_test_results:
      #     path: test-results
  package:
    <<: *defaults
      - run:
          name: build-binaries
          command: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - bin
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app/bin
      - run:
          name: publish release
          command: ghr -u Nike-Inc -r dabber $CIRCLE_TAG bin/
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - package:
          requires:
            - build
          filters:
            <<: *tag_filter
      - release:
          requires:
            - package
          filters:
            <<: *tag_filter